#ifndef MY_DEFINES_H
#define MY_DEFINES_H

#include <QString>

#define MAX_FILE_SIZE 10048576
#define DEFAULT_PACKET_SIZE 1024

const QString FORMAT = "yyyy-MM-dd hh:mm:ss";

enum clientToServerMessage {LOGIN, LOGOUT, REGISTER, PUSH_FILE, UPLOAD_THIS_FILE,SHARE_REQUEST, SEE_PREVIOUS_VERSION, RESTORE_VERSION, CANCEL_RESTORE};
enum serverToClientMessage {OK, NOT_OK, FILE_PRESENT, FILE_NOT_PRESENT, SEND_UPDATED_FILE, RECIEVE_UPDATED_FILE};

#endif // MYDEFINES_H
